### ISSUE TITLE
Organisation filter is too narrow

### ISSUE THREAD

**Issue by jamiecobbett** [alphagov/contacts-admin#169]
The organisation filter is far too narrow for the values that need to go in it.
![screen shot 2015-01-06 at 15 10 09](https://cloud.githubusercontent.com/assets/93739/5630482/21cf5140-95b6-11e4-88e9-5b545979fc55.png)

Additionally, with JavaScript turned off, it is far too wide.
![screen shot 2015-01-06 at 15 09 45](https://cloud.githubusercontent.com/assets/93739/5630478/12893d0e-95b6-11e4-9a09-093245bd8267.png)

**Comment by issyl0** [comment]
Arrghhhh, GitHub. I wish it wouldn't do that.
